name: buss_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:

  cloud_firestore: ^4.8.4
  firebase_core: ^2.15.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  google_maps_flutter: ^2.2.8
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1


dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  pedantic_mono:
  json_serializable: ^6.7.1
  freezed: ^2.4.2

flutter:
  uses-material-design: true

  assets:
    - images/
