name: buss_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:

  cloud_firestore: ^4.8.4
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.4.1
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.8
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  pedantic_mono:

flutter:
  uses-material-design: true

  assets:
    - images/
