name: buss_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:

  cloud_firestore: ^4.8.4 # https://pub.dev/packages/cloud_firestore
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0 # https://pub.dev/packages/firebase_core
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: 
  google_sign_in: ^6.1.4
  riverpod_annotation: ^2.1.1
  riverpod_generator: ^2.2.5

dev_dependencies:
  build_runner: 
  flutter_lints: ^2.0.0
  freezed: 
  json_serializable: 
  pedantic_mono:

flutter:
  uses-material-design: true

  assets:
    - images/
    - sakegawa_gtfs/
