name: buss_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  cloud_firestore: ^4.8.4
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.4.1
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.8
  json_annotation: ^4.8.1
  modal_bottom_sheet: ^3.0.0-pre
  riverpod_annotation: ^2.1.2
  url_launcher: ^6.0.9

dev_dependencies:
  build_runner: 
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.1.3+1
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  pedantic_mono:
  riverpod_generator: 

# すささんの記事（https://zenn.dev/flutteruniv_dev/articles/20220406-061305-flutter-native-splash?redirected=1）
# スプラッシュ生成コマンド (flutter pub run flutter_native_splash:create)
flutter_native_splash:
  color: '#0B131B'
  image: 'images/RiverPotter.jpg'
  color_dark: '#0B131B'
  image_dark: 'images/RiverPotter.jpg'
  fullscreen: true
  android_12:
    icon_background_color: '#0B131B'
    image: 'images/RiverPotter.jpg'
    icon_background_color_dark: '#0B131B'
    image_dark: 'images/RiverPotter.jpg'

flutter:
  uses-material-design: true

  assets:
    - images/
    - edamitsu/
