name: buss_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:

  cloud_firestore: ^3.2.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.4.0
  firebase_core: ^1.19.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  google_sign_in: ^6.1.4


dev_dependencies:
  build_runner: 
  flutter_lints: ^2.0.0
  pedantic_mono:

flutter:
  uses-material-design: true

  assets:
    - images/
